server:
  port: 0000

logging:
  level:
    root: EXAMPLE
    com.example: EXAMPLE

spring:
  datasource:
    url: EXAMPLE
    driver-class-name: EXAMPLE
    username: EXAMPLE
    password: EXAMPLE

  jpa:
    hibernate:
      ddl-auto: EXAMPLE
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: EXAMPLE

jwt:
  secret: EXAMPLE
  expiration: 0000